# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.NullBooleanField(verbose_name='url')),
            ],
        ),
    ]
