# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
